### ISSUE TITLE
New species property in Plant

### ISSUE THREAD

**Issue by philchayer** [philchayer/Bean#2]
Need a new property to set the plant species.  Instead of puting the species in the name with single quote (eg "Tomate 'Yellow cherry'"), it will be better to set the species in a property that contain only the species. 

Client side:
 Q? In the plant list page (plants), what is the best? 
   1. Add the species with single quote at the end of the name
   2. Add a new column "Species". This column will be available for the search

**Comment by Sabbistar** [comment]
Answer #1 is preferred by client.

**Comment by philchayer** [comment]
New property is added and available in plant details page. Like asked, the name display the name and the species in single quote.
